### ISSUE TITLE
Vue 方式使用咱们的组件实现的H5页面，从app里面跳转到H5页面的时候new SlideRuler不生效

### ISSUE THREAD

**Issue by liulingling19931206** [simbawus/slide-ruler#2]
hollo,您好，Vue 方式使用咱们的组件实现的H5页面，从app里面跳转到H5页面的时候new SlideRuler不生效，应该怎么解决呢，还是我用的方式不对嫩

**Comment by simbawus** [comment]
直接在浏览器打开是否可以呢？这个跟跳转来源应该是没有关系的

**Comment by simbawus** [comment]
有问题的手机是什么系统？系统版本？安卓版本多少？用什么浏览器打开？打开我的在线Demo有问题么？你们app 有缓存机制么？

**Comment by wtyang** [comment]
@simbawus 
http://www.fackyou.org/archives/nodejs/2017050424.html  是否有这个问题

**Comment by simbawus** [comment]
@wtyang 的确用到了这个api，不知道遇到的问题跟这个有没有关系？
@liulingling19931206 能否将这个链接（
https://simbawus.github.io/slide-ruler?console=true）放到你们app里，看页面悬浮的webconsole 是否有相关报错

**Comment by wtyang** [comment]
@simbawus  我放在手机端测试了，确实是三个标尺无法显示并且报错 `Object function Object() { [native code] } has no method 'assign'`  跟我提供那个情况一样。 安卓4.4.4

**Comment by simbawus** [comment]
@wtyang 好，谢谢。等我今晚修复好，关闭Issues你就可以更新了。

**Comment by wtyang** [comment]
经测试，加入object.assign 不报错了 期待修复！ 开源精神 给你点个赞

**Comment by simbawus** [comment]
谢谢啦，star是对我最好的赞美！🎻

**Comment by simbawus** [comment]
bug已修复，请更新到v1.0.1版本
