### ISSUE TITLE
想改成pc版

### ISSUE THREAD

**Issue by Hilbertangers** [simbawus/slide-ruler#3]
请问有解决方案吗，模拟touch？

**Comment by simbawus** [comment]
嗯 用mouse吧

**Comment by simbawus** [comment]
@Hilbertangers 使用场景是什么？或许我可以兼容下

**Comment by Hilbertangers** [comment]
@simbawus 场景：在pc页面使用，按住鼠标移动尺子。
（需求其实你都实现了，把三个touch事件模拟一下就ok了）。
其实我有想过在canvas上面盖一层透明的div，用scroll来取左右的滑动距离，不知道可不可行？

**Comment by simbawus** [comment]
@Hilbertangers 不可以 因为尺子的长度不是一次性渲染的 是实时渲染的 总长度只有容器宽度 不会出现滚动条。这么做的目的是，当尺子有一定的长度时，会有性能问题，造成卡顿，甚至浏览器渲染。

**Comment by Hilbertangers** [comment]
@simbawus 我提交了一个兼容的pr，有时间可以review下 #4

**Comment by simbawus** [comment]
谢谢，已经merge了，npm更新到v1.1.1版本就可以
