### ISSUE TITLE
支持Typescript

### ISSUE THREAD

**Issue by yuri147** [simbawus/slide-ruler#5]
希望能提供对Typescript的支持，提供 @types/slide-ruler

**Comment by simbawus** [comment]
原生JS写的，TS难道不能用？

**Comment by yuri147** [comment]
> 原生JS写的，TS难道不能用？

tslint 对未包含index.d.ts申明的包无法import

**Comment by simbawus** [comment]
tslint 对node_modules 不添加 ignore ？

**Comment by yuri147** [comment]
> tslint 对node_modules 不添加 ignore ？

TS7016: Could not find a declaration file for module

**Comment by yuri147** [comment]
只能require，无法import

**Comment by simbawus** [comment]
tsconfig.json 的noImplicitAny 设置为true就可以了
```json
"compilerOptions": {
    "noImplicitAny": true
  }
```

**Comment by yuri147** [comment]
暂时使用require替代
