### ISSUE TITLE
刻度会有大约两格的偏差

### ISSUE THREAD

**Issue by font-end-newbie** [simbawus/slide-ruler#8]
![image](https://user-images.githubusercontent.com/31084892/55147177-e1f36800-5180-11e9-95b5-8db5914d840a.png)
![image](https://user-images.githubusercontent.com/31084892/55147243-fb94af80-5180-11e9-9877-3083f35cac08.png)
初始默认值设置的是12，但是标识的位置在11.8

**Comment by font-end-newbie** [comment]
往后面拉会发现，的确位置偏移了两格，我的代码是直接照着demo来的。
![image](https://user-images.githubusercontent.com/31084892/55147602-a86f2c80-5181-11e9-8c3a-759a41b9c655.png)
![image](https://user-images.githubusercontent.com/31084892/55147644-b91fa280-5181-11e9-820b-c6750bdda86a.png)

**Comment by simbawus** [comment]
你的代码没问题，是不是本地的css对滑尺的指针有影响呢？

**Comment by font-end-newbie** [comment]
感谢，问题已经解决，是本地CSS对其产生了影响。还有一个问题就是，handleVue回调函数的值，我没有法子赋给其它的变量上，比如我在store里面有一个handsize，我在handlevalue的回调里面把value赋值给handsize发现值没有法子赋上

**Comment by simbawus** [comment]
1. 本地CSS是怎么影响的？我看我这边能不能做隔离。
2. 既然能取到handleValue的值，那滑尺组件已经完成它的使命了。赋值不成功，那应该是你写法的问题。

**Comment by font-end-newbie** [comment]
1.CSS影响是因为在尺子组件外我加了个外层容器，用了padding挤了下边距。

**Comment by simbawus** [comment]
好的 这个问题 我稍后会修复

**Comment by font-end-newbie** [comment]
感谢
